spring:
  application:
    name: linkedin_backend
  datasource:
    url: jdbc:postgresql://localhost:7001/hinkedin
    username: hinkedin
    password: hinkedin
  jpa:
    hibernate:
      ddl-auto: create # 每次重新启动时删除并重新创建
    show-sql: true
    properties:
      hibernate:
        format_sql: true