spring:
  application:
    name: linkedin_backend
  datasource:
    url: jdbc:postgresql://localhost:7001/hinkedin
    username: hinkedin
    password: hinkedin
  jpa:
    hibernate:
      ddl-auto: update # 开发时自动更新schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true