services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: hinkedin
      POSTGRES_PASSWORD: hinkedin
      POSTGRES_DB: hinkedin
    ports:
      - '7001:5432'    # 左边宿主机端口，右边容器内部端口，5432为postgresql默认端口

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'  # Web UI for viewing emails